### ISSUE TITLE
The example is not good

### ISSUE THREAD

**Issue by receita-digital** [117/repeat#1]
The code example is not clear how the function calls.
how is require () done?

The code below does not work

```javascript
repeat = require('repeat');
repeat()
  .do(() => console.log("how are you?"))
  .do(() => console.log("good"))
  .every(1000);
```

```
P:\testes\ex-git>node repeat.js
P:\testes\ex-git\repeat.js:2
repeat()
^

TypeError: repeat is not a function
    at Object.<anonymous> (P:\testes\ex-git\repeat.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

P:\testes\ex-git>
```

I suggest this code on README.md:

```node
repeat = require('repeat').default;

repeat()
  .do(() => console.log("how are you?"))
  .do(() => console.log("good"))
  .every(1000);
```

Sorry for my bad english

**Comment by xist** [comment]
The following is what I had in mind when writing the example.
```javascript
import require from "require"
``` 
But I do think an example for ES5 users should be provided, I'll add your solution until I can write-in backwards compatibility.

**Comment by xist** [comment]
😄  I've added backwards compatibility. Using version **1.1.4** you can now import like this:
```javascript
const repeat = require("repeat");
```
Make sure to update references and remove the `.default`.

**Comment by receita-digital** [comment]
Many thanks master.

**Comment by synth3tk** [comment]
> Make sure to update references and remove the `.default`.

FYI, with version 1.2.0 I still had to include `.default` in my ES5 code.

**Comment by 117** [comment]
> > Make sure to update references and remove the `.default`.
> 
> FYI, with version 1.2.0 I still had to include `.default` in my ES5 code.

Thanks for letting me know, I'll fix this later today in a new patch.

**Comment by 117** [comment]
> > Make sure to update references and remove the `.default`.
> 
> FYI, with version 1.2.0 I still had to include `.default` in my ES5 code.

```typescript
// ES6
import { Chain } from 'repeat'

// ES5
// let { Chain } = require('repeat')
```

The readme now includes both import examples, and the code base was updated but backwards compatibility remains.
