### ISSUE TITLE
Module cannot be found

### ISSUE THREAD

**Issue by idmadj** [117/repeat#8]
When importing (using either require or import), the module cannot be found. Happens locally as well as on https://npm.runkit.com/repeat:
```
Error: Cannot find module '/app/available_modules/1624500808000/repeat/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
```
Seems to be an issue with package.json's `main` pointing to `dist/src/index.js`, while the package actually has no `src` subfolder in `dist` (should be `"main": "dist/index.js"`)

Applies to 2.0.3

**Comment by 117** [comment]
Thanks for letting me know, I'll remedy this.
